if [[ -r ~/.powerlevel9k_font_mode ]]; then
  POWERLEVEL9K_MODE=$(head -1 ~/.powerlevel9k_font_mode)
fi

# powerlevel9k config
POWERLEVEL9K_MODE='nerdfont-complete'
# POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
# POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="↱"
# POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="↳ "
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="╭"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="╰\uF460 " # ╰
POWERLEVEL9K_CONTEXT_TEMPLATE="%F{yellow}%n%F{white}# @%F{green}%m"
# POWERLEVEL9K_CONTEXT_FOREGROUND='white'
# POWERLEVEL9K_CONTEXT_BACKGROUND='236' # Dark Grey
# POWERLEVEL9K_USER_FOREGROUND='yellow'
# POWERLEVEL9K_HOST_FOREGROUND='green'
# POWERLEVEL9K_HISTORY_FOREGROUND='red'
# POWERLEVEL9K_HISTORY_BACKGROUND='238' # Dark Grey
# POWERLEVEL9K_TIME_FOREGROUND='blue'
# POWERLEVEL9K_TIME_BACKGROUND='236' # Dark Grey
# POWERLEVEL9K_DIR_HOME_FOREGROUND='012'
# POWERLEVEL9K_DIR_HOME_BACKGROUND='236' # Dark Grey
# POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='012'
# POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='236' # Dark Grey
# POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='012'
# POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='236' # Dark Grey
#
# POWERLEVEL9K_VCS_CLEAN_FOREGROUND='yellow'
# POWERLEVEL9K_VCS_CLEAN_BACKGROUND='239'
# POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='yellow'
# POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='238'
# POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='red'
# POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='238'
# POWERLEVEL9K_VIRTUALENV_FOREGROUND='236'
POWERLEVEL9K_VIRTUALENV_BACKGROUND='080'

POWERLEVEL9K_TODO_ICON='\u2611'                  # ☑
POWERLEVEL9K_OK_ICON='\u2714'                    # ✔
POWERLEVEL9K_VPN_ICON='\uF023'                   # 
POWERLEVEL9K_FAIL_ICON='\u2718'                  # ✘
POWERLEVEL9K_NODE_ICON='\u2B22'                  # ⬢
# POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
# POWERLEVEL9K_VCS_UNSTAGED_ICON='!'
POWERLEVEL9K_VCS_STAGED_ICON='\u271A'            # ✚
POWERLEVEL9K_NETWORK_ICON='\uF09E'               # 
POWERLEVEL9K_VCS_GIT_ICON=' \uF1D3 '             # 
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=' \uF406 '      # 
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=' \uF296 '      # 
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=' \uE703 '   # 
POWERLEVEL9K_PYTHON_ICON=' \UE73C '              # 
# POWERLEVEL9K_HOME_ICON='\uF015 '               # 
# POWERLEVEL9K_HOME_SUB_ICON='\uF07C '           # 
# POWERLEVEL9K_FOLDER_ICON='\uF115 '             # 
# slant segment seperators
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B8'      # 
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B9'   # 
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0BA'     #  
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0BB'  #  
# # flames segment seperators
# POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0C0'     # 
# POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0C1'  # 
# POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0C2'    #  
# POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0C3' #  

POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S \uF017  %Y.%m.%d}"

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir rbenv virtualenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time)