cask_args appdir: "/Applications"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "buo/cask-upgrade"
tap "chef/chef"

brew "git"
brew "coreutils"
brew "findutils"
brew "rbenv"
brew "pyenv"
brew "go"
brew "bash"
brew "zsh"
brew "stow"
brew "mas"
brew "grc"
brew "wget"
brew "cmake"
brew "openssh"
brew "zlib"
brew "tmux"
brew "jq"

cask "1password"
cask "1password-cli"
cask "iterm2"
cask "docker"
cask "keybase"
cask "textmate"
cask "font-inconsolata-nerd-font"
cask "chefdk"

# cask "goole-chrome"
cask "firefox"

mas "Xcode", id: 497799835
mas "Browser Fairy", id: 483014855
mas "JSON Helper for AppleScript", id: 453114608
mas "Location Helper for AppleScript", id: 488536386
mas "Right Click Booster", id: 970432740
mas "LaunchD Task Schduler", id: 620249105
mas "Monosnap - screenshot editor", id: 540348655
